//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fdistribution
    {
        public int id { get; set; }
        public string resname { get; set; }
        public int employeeid { get; set; }
        public System.DateTime date { get; set; }
        public int exdate { get; set; }
        public string instruction { get; set; }
    }
}
