//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurent
    {
        public int id { get; set; }

        public string restaurentname { get; set; }
        public string address { get; set; }
        public string password { get; set; }

        public string Confirmpassword { get; set; }
    }
}
